apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongodb
  template:
    metadata:
      labels:
        service: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        volumeMounts:
        - name: mongo-volume-mount
          mountPath: /data/db
      restartPolicy: Always
      volumes:
      - name: mongo-volume-mount
        persistentVolumeClaim:
          claimName: mongo-persistent-volume-claim