apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-persistent-volume
  labels:
    name: mongo-persistent-volume
spec:
  capacity:
    storage: 50Gi
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: mongodb-data-disk
    fsType: ext4