apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc2
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 50Gi
  volumeName: mongo-pv2
