apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv2
  labels:
    name: mongo-pv2
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: mongo-data-disk
    fsType: ext4